version: '1.0'

services:

  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
      - ./app/package.json:/app/package.json
    ports:
      - 3000:3000
  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - ./api/:/app/
    ports:
      - 5050:5050
    env_file:
      - ./api/.env