version: '1.0'

services:

  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
      - ./app/package.json:/app/package.json
    env_file:
      - ./.env
    ports:
      - 3000:3000